---
title: "Project_example"
author: "Chih-Hui(Jason) Wang"
date: "November 21, 2015"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment='')
knitr::opts_chunk$set(fig.align='center')
```

# Standard normal distribution as example

```{r}
#Standard normal(log scale)
logdnorm <- function(x){
  -x^2/2 - log(2*pi)/2
}

#Derivative
logddnorm <- function(x){
  -x
}
```

# Main function pseudo code
```{r}
experiment <- function(n, k, density_fun, ddensity_fun){
  #Initital value

  #z
  
  #Compute u
  
  #Compute s
  
  #Compute l
  
  #Sampling step for x_star
  
  #Sampling step for w
  
  #Reject or not
  
  #Updating step
  
  #Output
  
}
```

# u and l function
```{r}
#Function generate coefficient and breaks
generate_u <- function(x, fun, fun_deriv){
  z <- (fun(x[-1]) - fun(x[-k]) - x[-1]*fun_deriv(x[-1]) + x[-k]*fun_deriv(x[-k]))/(fun_deriv(x[-k]) - fun_deriv(x[-1]))
  
  #Construct upper and lower bound
  z <- c(-Inf, z, Inf)
  
  #Grouping
  group <- cut(x, breaks=z, labels=1:length(x))
  #Check which group the x1 locate
  xj <- x[as.numeric(group)]
  
  #Compute value, slope and intercept
  value <- fun(xj) + (x - xj)*fun_deriv(xj)
  a <- fun_deriv(x)
  b <- fun(x) - a*x
  
  out <- list(parameter=cbind(a, b), breaks=z)
  out
}

l <- function(x1, x, fun){
  #Grouping
  group <- cut(x1, breaks=x, labels=1:(length(x) - 1))
  #Check which group the x1 locate
  xj <- x[as.numeric(group)]
  xjplus <- x[as.numeric(group) + 1]
  
  #Compute value
  all <- ((xjplus - x1)*fun(xj) + (x1 - xj)*fun(xjplus))/(xjplus - xj)
  all[is.na(all)] <- -Inf
  
  all
}

area <- function(z, u){
  area <- rep(0, length(z) + 1)
  #Add upper and lower bound
  z <- c(-Inf, z, Inf)
  for(i in 1:length(area)){
    #Update Coefficient
    a <- u$parameter[i, 1]
    b <- u$parameter[i, 2]
    
    #Compute area under the exponential
    area[i] <- integrate(function(x, a, b) exp(a*x + b), z[i], z[i + 1], a=a, b=b)$value
  }
  
  area
}
```

```{r}
#Initial point -0.5, 0.5
#5 abscissaes
k <- 5
x <- seq(-0.5, 0.5, length.out=k)

generate_u(x, logdnorm, logddnorm)
```

### Intersection, upper and lower

```{r, eval=FALSE, echo=FALSE}
#Density
plot(seq(-1, 1, by=0.01), logdnorm(seq(-1, 1, by=0.01)), type="l", ylim=c(-1.1, -0.9))

#Abscissae
abline(v=x, lty=2)
#Intersect
abline(v=z, lty=2, col="blue")

#Add upper and lower
x1 <- seq(-1, 1, by=0.01)
lines(x1, u(x1, x, z, logdnorm, logddnorm)$u, col="green")
lines(x1, l(x1, x, logdnorm), col="orange")

legend("topright", lty=c(2, 1, 1), col=c("blue","green","orange"), legend=c("intersection", "upper", "lower"))
```

### Upper function
```{r, eval=FALSE, echo=FALSE}
#For visualize I take an x with larger range
x2 <- seq(-5, 5, by=0.1)
u2 <- u(x2, x, z, logdnorm, logddnorm)
plot(x2, exp(u2$u), type="l")
#Intersect
abline(v=z, lty=2, col="blue")

#For compute area, we only need those points in Abscissae
u1 <- u(x, x, z, logdnorm, logddnorm)
area(z, u1)
```


